### ISSUE TITLE
Change constants to enums

### ISSUE THREAD

**Issue by jamietypovsky** [Senzing/g2command#41]

**Comment by docktermj** [comment]
According to https://www.python.org/dev/peps/pep-0008/#constants

> Constants are usually defined on a module level and written in all capital letters with underscores separating words. Examples include MAX_OVERFLOW and TOTAL.

There are no constants defined in `G2Command.py`.

Please clarify the request.

**Comment by docktermj** [comment]
Is this referring to the style of Senzing imports?  If so the issue is https://github.com/Senzing/g2command/issues/32

**Comment by docktermj** [comment]
Moved to https://github.com/Senzing/g2-sdk-python/issues/93
